ci: Move sanitizers task from Cirrus to GitHub Actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -373,6 +373,79 @@ jobs:
         run: env
         if: ${{ always() }}
 
+  sanitizers_debian:
+    name: ${{ matrix.configuration.job_name }}
+    runs-on: ubuntu-latest
+    needs: docker_cache
+
+    strategy:
+      fail-fast: false
+      matrix:
+        configuration:
+          - job_name: 'Valgrind (memcheck)'
+            env_vars:
+              # The `--error-exitcode` is required to make the test fail if valgrind found errors,
+              # otherwise it will return 0 (https://www.valgrind.org/docs/manual/manual-core.html).
+              WRAPPER_CMD: 'valgrind --error-exitcode=42'
+              SECP256K1_TEST_ITERS: 2
+          - job_name: 'UBSan, ASan, LSan'
+            env_vars:
+              CFLAGS: '-fsanitize=undefined,address -g'
+              UBSAN_OPTIONS: 'print_stacktrace=1:halt_on_error=1'
+              ASAN_OPTIONS: 'strict_string_checks=1:detect_stack_use_after_return=1:detect_leaks=1'
+              LSAN_OPTIONS: 'use_unaligned=1'
+              SECP256K1_TEST_ITERS: 32
+        asm:
+          - env_vars: { ASM: 'auto' }
+          - env_vars: { ASM: 'no', ECMULTGENPRECISION: 2, ECMULTWINDOW: 2 }
+        cc:
+          - env_vars: { CC: 'clang' }
+          - env_vars: { HOST: 'i686-linux-gnu', CC: 'i686-linux-gnu-gcc' }
+
+    env:
+      ECDH: 'yes'
+      RECOVERY: 'yes'
+      SCHNORRSIG: 'yes'
+      ELLSWIFT: 'yes'
+      CTIMETESTS: 'no'
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Set environment variables
+        run: |
+          for var in "$(jq -s 'add' <<< '${{ toJSON(matrix.configuration.env_vars) }} ${{ toJSON(matrix.asm.env_vars) }} ${{ toJSON(matrix.cc.env_vars) }}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"')"; do
+            echo "$var" >> "$GITHUB_ENV"
+          done          
+
+      - name: CI script
+        uses: ./.github/actions/run-in-docker-action
+        with:
+          dockerfile: ./ci/linux-debian.Dockerfile
+          tag: linux-debian-image
+          command: >
+            git config --global --add safe.directory ${{ github.workspace }} &&
+            ./ci/ci.sh
+
+      - run: cat tests.log || true
+        if: ${{ always() }}
+      - run: cat noverify_tests.log || true
+        if: ${{ always() }}
+      - run: cat exhaustive_tests.log || true
+        if: ${{ always() }}
+      - run: cat ctime_tests.log || true
+        if: ${{ always() }}
+      - run: cat bench.log || true
+        if: ${{ always() }}
+      - run: cat config.log || true
+        if: ${{ always() }}
+      - run: cat test_env.log || true
+        if: ${{ always() }}
+      - name: CI env
+        run: env
+        if: ${{ always() }}
+
   mingw_debian:
     name: ${{ matrix.configuration.job_name }}
     runs-on: ubuntu-latest
